FROM node:22-alpine AS build
WORKDIR /srv
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
ENV NEXT_PUBLIC_API_URL=http://localhost:8000
ENV NEXT_PUBLIC_WS_URL=ws://localhost:8000
RUN npm run build

FROM nginx:alpine
COPY --from=build /srv/out /usr/share/nginx/html
COPY nginx.local.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
